/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#002c4f",
        "on-secondary-container": "#56656e",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#b0c6ff",
        "tertiary-fixed": "#d9e2ff",
        "outline-variant": "#bfc7d4",
        "on-secondary-fixed-variant": "#3b4951",
        "surface": "#f9f9f9",
        "primary-fixed": "#d1e4ff",
        "background": "#f9f9f9",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#0f1d25",
        "on-surface-variant": "#404752",
        "inverse-primary": "#9ecaff",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#00429c",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d3e2ed",
        "on-primary-fixed-variant": "#00497d",
        "surface-container": "#eeeeee",
        "secondary-fixed": "#d6e5ef",
        "outline": "#707883",
        "on-tertiary-container": "#002763",
        "secondary": "#526069",
        "surface-container-low": "#f3f3f4",
        "on-surface": "#1a1c1c",
        "primary-fixed-dim": "#9ecaff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#001945",
        "surface-tint": "#0061a4",
        "tertiary": "#2b5bb5",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f0f1f1",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary": "#0061a4",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "on-error": "#ffffff",
        "primary-container": "#2196f3",
        "on-primary-fixed": "#001d36",
        "surface-variant": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "secondary-fixed-dim": "#bac9d3",
        "tertiary-container": "#658fed"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-lg": "32px",
        "base": "8px"
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl-mobile": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["36px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
